#!/bin/bash

echo "BI Team Analyzer Setup Script"
echo "=============================="
echo ""
echo "This script will help you set up the application."
echo ""
echo "Step 1: Fix npm cache permissions (requires sudo)"
echo "Run: sudo chown -R $(whoami) ~/.npm-cache"
echo ""
echo "Step 2: Install dependencies"
echo "Run: npm install --force"
echo ""
echo "Step 3: Start development server"
echo "Run: npm run dev"
echo ""
echo "For deployment to Vercel:"
echo "Run: npx vercel"
echo ""
echo "Note: The application will run on http://localhost:3000"